### ISSUE TITLE
more archives

### ISSUE THREAD

**Issue by roytam1** [the-grue/OpenDOS#1]
Don't know if you want to archive more or not, I posted some of my collected patch/source archives here:

older WIP patch:
[d090723p.zip](https://github.com/the-grue/OpenDOS/files/11280527/d090723p.zip)

country.sys source patch:
[countrp.zip](https://github.com/the-grue/OpenDOS/files/11280532/countrp.zip)

FreeDOS `format` modified for EDR-DOS:
[drfmt10s.zip](https://github.com/the-grue/OpenDOS/files/11280534/drfmt10s.zip)

FreeDOS `sys` modified for EDR-DOS:
[drsys35s.zip](https://github.com/the-grue/OpenDOS/files/11280538/drsys35s.zip)

FreeDOS `xcopy` modified for EDR-DOS:
[dxcpy14s.zip](https://github.com/the-grue/OpenDOS/files/11280542/dxcpy14s.zip)

EDR-DOS kernel packer script:
[pack101.zip](https://github.com/the-grue/OpenDOS/files/11280548/pack101.zip)

**Comment by the-grue** [comment]
Good morning @roytam1!  Please direct these to the edrdos project.  The OpenDOS repo is mostly a historical artifact at this point to keep the files available at a point in time for those interested.

I am cloning the edrdos project's Mercurial repo here https://github.com/the-grue/edrdos

The original is located here https://hg.pushbx.org/ecm/edrdos/
