### ISSUE TITLE
EDR-DOS repository as of 2023

### ISSUE THREAD

**Issue by Torinde** [the-grue/OpenDOS#2]
As discussed at ecm-pushbx/8086tiny/issues/3 - there is an active [forum](https://www.bttr-software.de/forum/mix_entry.php?id=20457) and [hg repository](https://hg.pushbx.org/ecm/edrdos) for EDR-DOS - to the 2011 sources is added the new license plus some other changes, 

If you can somehow 'mirror' that in GitHub, I think it would be useful.

**Comment by the-grue** [comment]
Mirrored at https://github.com/the-grue/edrdos
